# Generated by Django 4.2.4 on 2023-08-14 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_product_cat_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Cat_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.cat_list', verbose_name='Катигория'),
        ),
    ]
