# Generated by Django 4.2.4 on 2023-08-14 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_product_cat_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукция'},
        ),
        migrations.AlterField(
            model_name='product',
            name='Cat_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.cat_list', verbose_name='Катигория'),
        ),
    ]
